"""Lightweight build progress tracking for derived builds.

Reports structured progress to the run log and an optional state file so that
external monitors (and the daily orchestrator) can see:

* current stage (PLANNING, BUILDING_PARTITIONS, COMMITTING, …)
* processed / total / failed counts
* current security_id
* throughput (partitions per minute)
* heartbeat timestamp

Two distinct identities are carried in every snapshot:

* ``progress_contract_id`` — the orchestrator↔child progress monitoring
  protocol identity. Unique per (run_instance, step). Generated by the
  orchestrator BEFORE spawn and passed via
  ``QDC_DERIVED_PROGRESS_CONTRACT_ID``. The stall detector verifies that the
  snapshot it reads was written for this exact contract id.
* ``journal_run_id`` — the derived build journal's stable recovery identity.
  Stable across resume: a resumed run keeps the old journal run id while
  getting a fresh ``progress_contract_id``.

The reporter is intentionally throttled: it writes at most once every
``min_interval_seconds`` or every ``flush_every`` partitions, whichever comes
first. This avoids I/O overhead in the hot loop.
"""

from __future__ import annotations

import json
import time
import uuid
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from threading import RLock
from typing import Any

from src.utils.logging import logger

STAGE_PLANNING = "PLANNING"
STAGE_REPAIRING_MANIFEST = "REPAIRING_MANIFEST"
STAGE_BUILDING_PARTITIONS = "BUILDING_PARTITIONS"
STAGE_COMMITTING = "COMMITTING"
STAGE_REFRESHING_VIEWS = "REFRESHING_VIEWS"
STAGE_COMPLETED = "COMPLETED"
STAGE_FAILED = "FAILED"
STAGE_CANCELLING = "CANCELLING"
STAGE_CANCELLED = "CANCELLED"

DEFAULT_FLUSH_INTERVAL_SECONDS = 30.0
DEFAULT_FLUSH_EVERY = 50

PROGRESS_SNAPSHOT_SCHEMA_VERSION = 1


@dataclass(frozen=True)
class ProgressIdentity:
    """Immutable identity carried in every progress snapshot.

    Attributes:
        progress_contract_id: Orchestrator↔child progress monitoring protocol
            identity. Unique per (run_instance, step). The stall detector
            verifies that the snapshot it reads was written for this exact id.
        target: Derived target name (``daily_bar``, ``valuation``, ...).
        dataset_id: Underlying dataset id (``cn_stock_daily_bar``, ...).
        journal_run_id: Derived build journal's stable recovery identity.
            Stable across resume; the progress_contract_id is NOT stable
            across resume.
    """

    progress_contract_id: str
    target: str
    dataset_id: str
    journal_run_id: str


def make_progress_contract_id(step_id: str) -> str:
    """Generate a unique progress contract id for one derived step.

    The format ``derived-progress:<step_id>:<uuid_hex>`` is collision-proof
    across concurrent orchestrator invocations and across same-second
    restarts. The step id is included for forensic readability; the uuid
    is the actual uniqueness guarantee.
    """

    return f"derived-progress:{step_id}:{uuid.uuid4().hex}"


@dataclass
class ProgressState:
    """Mutable progress state. Reads are snapshot-consistent under the lock."""

    stage: str = STAGE_PLANNING
    processed: int = 0
    total: int = 0
    failed: int = 0
    current_security_id: str | None = None
    started_at: datetime = field(default_factory=datetime.now)
    heartbeat_at: datetime = field(default_factory=datetime.now)
    last_flush_at: float = field(default_factory=time.monotonic)
    failed_security_ids: list[str] = field(default_factory=list)

    def snapshot(self, identity: ProgressIdentity | None = None) -> dict[str, Any]:
        elapsed = max((datetime.now() - self.started_at).total_seconds(), 0.1)
        throughput = (self.processed / elapsed) * 60.0 if self.processed else 0.0
        snapshot: dict[str, Any] = {
            "schema_version": PROGRESS_SNAPSHOT_SCHEMA_VERSION,
            "stage": self.stage,
            "processed": self.processed,
            "total": self.total,
            "failed": self.failed,
            "current_security_id": self.current_security_id,
            "throughput_per_minute": round(throughput, 2),
            "heartbeat_at": datetime.now().isoformat(timespec="seconds"),
            "started_at": self.started_at.isoformat(timespec="seconds"),
            "failed_security_ids": list(self.failed_security_ids),
        }
        if identity is not None:
            snapshot["progress_contract_id"] = identity.progress_contract_id
            snapshot["journal_run_id"] = identity.journal_run_id
            snapshot["target"] = identity.target
            snapshot["dataset_id"] = identity.dataset_id
        return snapshot


class ProgressReporter:
    """Thread-safe progress reporter with throttled state-file writes."""

    def __init__(
        self,
        *,
        state_path: Path | None = None,
        run_log_path: Path | None = None,
        flush_interval_seconds: float = DEFAULT_FLUSH_INTERVAL_SECONDS,
        flush_every: int = DEFAULT_FLUSH_EVERY,
        clock: Callable[[], float] | None = None,
        identity: ProgressIdentity | None = None,
    ) -> None:
        self._state_path = state_path
        self._run_log_path = run_log_path
        self._flush_interval = flush_interval_seconds
        self._flush_every = flush_every
        self._clock = clock or time.monotonic
        self._identity = identity
        self._lock = RLock()
        self._state = ProgressState()

    @property
    def state(self) -> ProgressState:
        return self._state

    @property
    def identity(self) -> ProgressIdentity | None:
        """The immutable progress identity, or ``None`` for legacy callers."""

        return self._identity

    def set_stage(self, stage: str, *, total: int | None = None) -> None:
        with self._lock:
            self._state.stage = stage
            if total is not None:
                self._state.total = total
            self._state.heartbeat_at = datetime.now()
        self._maybe_flush(force=True)

    def record_processed(self, security_id: str | None = None) -> None:
        with self._lock:
            self._state.processed += 1
            self._state.current_security_id = security_id
            self._state.heartbeat_at = datetime.now()
        self._maybe_flush()

    def record_failed(self, security_id: str) -> None:
        with self._lock:
            self._state.failed += 1
            self._state.failed_security_ids.append(security_id)
            self._state.heartbeat_at = datetime.now()
        self._maybe_flush()

    def heartbeat(self) -> None:
        with self._lock:
            self._state.heartbeat_at = datetime.now()
        self._maybe_flush(force=True)

    def final(self, stage: str = STAGE_COMPLETED) -> dict[str, Any]:
        with self._lock:
            self._state.stage = stage
            self._state.heartbeat_at = datetime.now()
            snapshot = self._state.snapshot(self._identity)
        self._write_state(snapshot)
        self._write_log(snapshot)
        return snapshot

    def snapshot(self) -> dict[str, Any]:
        with self._lock:
            return self._state.snapshot(self._identity)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _maybe_flush(self, *, force: bool = False) -> None:
        with self._lock:
            now = self._clock()
            time_due = (now - self._state.last_flush_at) >= self._flush_interval
            count_due = self._state.processed > 0 and self._state.processed % self._flush_every == 0
            if not force and not time_due and not count_due:
                return
            self._state.last_flush_at = now
            snapshot = self._state.snapshot(self._identity)
        self._write_state(snapshot)
        if count_due or force:
            self._write_log(snapshot)

    def _write_state(self, snapshot: dict[str, Any]) -> None:
        if self._state_path is None:
            return
        try:
            self._state_path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self._state_path.with_suffix(".tmp")
            tmp.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2), encoding="utf-8")
            tmp.replace(self._state_path)
        except OSError:
            logger.warning("Failed to write derived progress state to {}", self._state_path)

    def _write_log(self, snapshot: dict[str, Any]) -> None:
        line = (
            f"[derived-progress] stage={snapshot['stage']} "
            f"processed={snapshot['processed']}/{snapshot['total']} "
            f"failed={snapshot['failed']} "
            f"current={snapshot['current_security_id']} "
            f"throughput={snapshot['throughput_per_minute']}/min"
        )
        if self._run_log_path is not None:
            try:
                with self._run_log_path.open("a", encoding="utf-8") as handle:
                    handle.write(line + "\n")
            except OSError:
                pass
        logger.info(line)


# ---------------------------------------------------------------------------
# Stall detection (consumed by the orchestrator)
# ---------------------------------------------------------------------------


DEFAULT_STALL_HEARTBEAT_SECONDS = 25 * 60  # 25 minutes
DEFAULT_SAFETY_TIMEOUT_SECONDS = 18 * 60 * 60  # 18 hours


@dataclass(frozen=True)
class StallReport:
    """Result of a stall check on a derived build's progress state file."""

    stalled: bool
    reason: str | None
    heartbeat_age_seconds: float
    processed: int
    total: int


def read_progress_state(state_path: Path) -> dict[str, Any] | None:
    """Read the most recent progress state snapshot, or ``None`` if missing."""

    if not state_path.exists():
        return None
    try:
        data = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def check_stall(
    state_path: Path,
    *,
    now: datetime | None = None,
    stall_heartbeat_seconds: float = DEFAULT_STALL_HEARTBEAT_SECONDS,
    previous_processed: int | None = None,
    expected_contract_id: str | None = None,
) -> StallReport:
    """Check whether a derived build is stalled.

    A build is stalled when **all** of the following are true:

    1. The progress state file exists (build has started).
    2. The stage is not terminal (``COMPLETED`` / ``FAILED`` / ``CANCELLED``).
    3. The heartbeat is older than ``stall_heartbeat_seconds``.
    4. ``processed`` has not changed since the previous check.

    Condition 4 requires the caller to pass the previous ``processed`` value
    from the prior poll. On the first poll (``previous_processed=None``), only
    conditions 1-3 are checked.

    Identity verification (P0-2): when ``expected_contract_id`` is provided,
    a snapshot whose ``progress_contract_id`` does not match is treated as
    "not the contract we are monitoring" — the snapshot is NOT used to judge
    stalled, a mismatch is logged, and the detector continues waiting for the
    correct snapshot or the safety timeout. This prevents a stale file from a
    previous or concurrent run from masking a real stall or stall a healthy
    build.

    The caller (orchestrator) is expected to poll this every 60 seconds and
    terminate the child process when ``stalled`` is ``True``.
    """

    reference = now or datetime.now()
    snapshot = read_progress_state(state_path)
    if snapshot is None:
        return StallReport(
            stalled=False,
            reason="state file not found (build may not have started yet)",
            heartbeat_age_seconds=0.0,
            processed=0,
            total=0,
        )
    # Identity check: if the caller pinned a specific progress_contract_id,
    # a snapshot with a different (or missing) id must NOT influence the stall
    # verdict. We log and treat it as "not our contract" — keep waiting.
    if expected_contract_id is not None:
        snapshot_contract = str(snapshot.get("progress_contract_id") or "")
        if snapshot_contract != expected_contract_id:
            logger.warning(
                "Progress snapshot contract mismatch: expected={} actual={} path={}; "
                "ignoring snapshot for stall detection",
                expected_contract_id,
                snapshot_contract,
                state_path,
            )
            return StallReport(
                stalled=False,
                reason=(
                    f"progress_contract_id mismatch (expected={expected_contract_id!r}, "
                    f"actual={snapshot_contract!r}); waiting for correct snapshot"
                ),
                heartbeat_age_seconds=0.0,
                processed=0,
                total=0,
            )
    stage = str(snapshot.get("stage", ""))
    if stage in {STAGE_COMPLETED, STAGE_FAILED, STAGE_CANCELLED}:
        return StallReport(
            stalled=False,
            reason=f"stage is terminal: {stage}",
            heartbeat_age_seconds=0.0,
            processed=int(snapshot.get("processed", 0)),
            total=int(snapshot.get("total", 0)),
        )
    heartbeat_str = snapshot.get("heartbeat_at")
    heartbeat_at = _parse_iso_timestamp(heartbeat_str)
    if heartbeat_at is None:
        return StallReport(
            stalled=False,
            reason="heartbeat_at missing or unparseable",
            heartbeat_age_seconds=0.0,
            processed=int(snapshot.get("processed", 0)),
            total=int(snapshot.get("total", 0)),
        )
    age = (reference - heartbeat_at).total_seconds()
    processed = int(snapshot.get("processed", 0))
    total = int(snapshot.get("total", 0))
    if age < stall_heartbeat_seconds:
        return StallReport(
            stalled=False,
            reason=f"heartbeat is fresh ({age:.0f}s old)",
            heartbeat_age_seconds=age,
            processed=processed,
            total=total,
        )
    if previous_processed is not None and processed != previous_processed:
        return StallReport(
            stalled=False,
            reason=f"processed changed ({previous_processed} → {processed})",
            heartbeat_age_seconds=age,
            processed=processed,
            total=total,
        )
    return StallReport(
        stalled=True,
        reason=(
            f"heartbeat {age:.0f}s old (threshold {stall_heartbeat_seconds:.0f}s) "
            f"and processed unchanged at {processed}/{total}"
        ),
        heartbeat_age_seconds=age,
        processed=processed,
        total=total,
    )


def latest_progress_state_path(metadata_dir: Path, target: str) -> Path | None:
    """Find the most recent progress state file for the given target.

    Progress state files are named ``<run_id>.state.json`` under
    ``metadata_dir/derived-runs/``. We pick the most recently modified one
    whose journal (``<run_id>.json`` alongside it) has ``status=running``.
    """

    runs_dir = metadata_dir / "derived-runs"
    if not runs_dir.exists():
        return None
    candidates: list[tuple[Path, float]] = []
    for state_path in runs_dir.glob("*.state.json"):
        journal_path = state_path.with_suffix("")  # strip .state.json → .json
        # state path is <run_id>.state.json; journal is <run_id>.json
        journal_path = state_path.parent / state_path.name.replace(".state.json", ".json")
        if not journal_path.exists():
            continue
        try:
            journal_data = json.loads(journal_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(journal_data, dict):
            continue
        if str(journal_data.get("target")) != target:
            continue
        if str(journal_data.get("status")) != "running":
            continue
        try:
            mtime = state_path.stat().st_mtime
        except OSError:
            continue
        candidates.append((state_path, mtime))
    if not candidates:
        return None
    candidates.sort(key=lambda item: item[1], reverse=True)
    return candidates[0][0]


def _parse_iso_timestamp(value: object) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None
